# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build with batching
trigger:
  branches:
    include:
      - master
    exclude:
      - feature/upgradelab
pr:
  branches:
    include:
      - "*"
    exclude:
      - feature/upgradelab

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: "Bash 1"
  inputs:
    targetType: 'inline'
    script: 'echo ''Hello world 1'''
- task: Bash@3
  displayName: "Bash 2"
  inputs:
    targetType: 'inline'
    script: 'echo ''Hello world 2'''
- task: Bash@3
  displayName: "Bash 3"
  inputs:
    targetType: 'inline'
    script: 'echo ''Hello world 3'''
- task: Bash@3
  displayName: "Bash 4"
  inputs:
    targetType: 'inline'
    script: 'echo ''Hello world 4'''


